# Нейронные сети. Основы

## Реализация перцептрона

Перцептрон - это модель, предложенная Френком Розенблаттом в 1957 году и являющаяся прообразом современных нейронных сетей. По своей сути она представляет из себя значительно упрощенную схему восприятия информации мозгом. Целью этого практического задания будет реализация собственной модели перцептрона. Давайте разберем схему работы этого алгоритма в деталях.

* Мы работаем с тренировочной выборкой $S = \{(x_i, y_i)| i \in \{1,...,m\} \}$
* Инициализируем веса $\omega^{(0)} \leftarrow 0$ нулевым вектором.
* Инициализирует bias параметр $b = 0$.
* В начальный момент времени номер шага $t=0$.
* Задаем learning rate $\eta > 0$.
* Пока значение $t < t_{\max}$
    * случайно выбираем объект из тренировочной выборки $(x_i, y_i) \in S$.
    * если выполняется условие $y_i (\langle \omega^{(t)}, x_i\rangle + b) \leq 0$ тогда
        * $b^{(t+1)} \leftarrow b^{(t)} + \eta \times y_i$.
        * $\omega^{(t+1)} \leftarrow \omega^{(t)} + \eta \times y_i \times x_i$.
    * далее, обновляем $t \leftarrow t+1$.

Таким образом, финальное значение ветора весов $\omega$ и bias параметра $b$ позволяют классифицировать новый объект $x$. Если $(\langle \omega, x \rangle + b) \geq 0$, то мы относим объект к классу $+1$, в противном случае мы относим объект к классу $-1$.

Для начала загрузим датасет для задачи классификации цветков Ириса с помощь функции `load_iris` из `sklearn.datasets`. Давайте подготовим данные для задачи бинарной классификации. Для этого выберем первые 100 элементов из данного набора данных. Так же преобразуем класс $0$ в класс $-1$.

In [5]:
import numpy as np
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)
X, y = X[:100], y[:100]
print(X, y)
num_features = X.shape[1]
print(num_features)
y = np.array([1 if y_i == 1 else -1 for y_i in y])
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Реализуйте алгоритм перцептрона приведенный выше. Для выборки случайного объекта из тренировочного датасета по индексу используйте функцию `randint` из модуля `random` с параметрами 0 и n, где n - это размер тренировочно выборки. Перед запуском итераций алгоритма установите `random.seed(42)`. Вы можете реализовать перцептрон в качестве класса с интерфейсом, похожим на интерфейсы моделей из `scikit-learn`. Для этого достаточно реализовать функцию `fit` и `predict` для решения этого практического задания. Однако, ваша реализация может отличаться. Необходимое требование - это использование генератора случайных чисел, описанного выше.

### *РЕШЕНИЕ*

In [41]:
import random
random.seed(42)
    
class Perceptron4:      
    
    def __init__(self, b, eta, t):
        self.b = 0
        self.eta = eta
        self.t = t    
        self.w  = np.zeros(b)               
    
    def model_ros(self, x):       
        return 1 if (np.dot(x, self.w) + self.b >= 0) else -1    
    
    def predict(self, X):
        Y = []
        for x in X:
            result = self.model_ros(x)
            Y.append(result)          
        return np.array(Y)
    
    def fit(self, X, y):       
        wt_matrix = []        
        for k in range(self.t):
            i = random.randint(0, len(y)-1)            
            # updating the weights                     
            y_pred = self.model_ros(X[i])           
            
            if y[i] == 1 and y_pred == -1:
                self.w = self.w + self.eta * y[i] * X[i]
                self.b = self.b + self.eta * y[i]
            elif y[i] == -1 and y_pred == 1:
                self.w = self.w + self.eta * y[i] * X[i]
                self.b = self.b + self.eta * y[i]                 
            wt_matrix.append(self.w) 
            print('wt_matrix =  ', wt_matrix)       
        return np.array(wt_matrix)



Следующим шагом является проверка нашей модели. Случайно разделите выборку на тренировочный и тестовый датасет, используя функцию `tran_test_split` с параметрами `test_size=0.25` и `random_state=10`. Запустите обучение модели с параметрами $\eta=0.1$ и $t_{\max}=40$. Оцените качество на тестовой выборке и запишите результат в переменную `score` с точность до двух знаков после запятой, используя метрику `accuracy`. Это значение и будет являться ответом на это практическое задание.

### *РЕШЕНИЕ*

In [42]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=10)
model = Perceptron4(num_features, 0.1, 40)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
#score = mean_squared_error(y_test, y_pred)
score = round(accuracy_score(y_test, y_pred), 2)
print(score)

wt_matrix =   [array([-0.53, -0.37, -0.15, -0.02])]
wt_matrix =   [array([-0.53, -0.37, -0.15, -0.02]), array([-0.53, -0.37, -0.15, -0.02])]
wt_matrix =   [array([-0.53, -0.37, -0.15, -0.02]), array([-0.53, -0.37, -0.15, -0.02]), array([-0.53, -0.37, -0.15, -0.02])]
wt_matrix =   [array([-0.53, -0.37, -0.15, -0.02]), array([-0.53, -0.37, -0.15, -0.02]), array([-0.53, -0.37, -0.15, -0.02]), array([ 0.04, -0.08,  0.27,  0.11])]
wt_matrix =   [array([-0.53, -0.37, -0.15, -0.02]), array([-0.53, -0.37, -0.15, -0.02]), array([-0.53, -0.37, -0.15, -0.02]), array([ 0.04, -0.08,  0.27,  0.11]), array([ 0.04, -0.08,  0.27,  0.11])]
wt_matrix =   [array([-0.53, -0.37, -0.15, -0.02]), array([-0.53, -0.37, -0.15, -0.02]), array([-0.53, -0.37, -0.15, -0.02]), array([ 0.04, -0.08,  0.27,  0.11]), array([ 0.04, -0.08,  0.27,  0.11]), array([ 0.04, -0.08,  0.27,  0.11])]
wt_matrix =   [array([-0.53, -0.37, -0.15, -0.02]), array([-0.53, -0.37, -0.15, -0.02]), array([-0.53, -0.37, -0.15, -0.02]), array([

# Строка с ответами

In [40]:
print("score {0:.2f}".format(score))

score 1.00
